### ISSUE TITLE
Single File publishing in window service does not read appsetting.json

### ISSUE THREAD

**Issue by zraffaele** [dotnet/designs#85] opened 2019-12-04 11:11 UTC
This the steps for reproduce the issue:
-Publish .net core project as single file exe
-Exclude from single file appsetting.json (of course in customer server the appsettings it is not the same like in the client configuration) with this settings in the .csproj 
Content Include="*.json"
     CopyToOutputDirectory-PreserveNewest-CopyToOutputDirectory
     ExcludeFromSingleFile-true-/ExcludeFromSingleFile
 Content
and 
EnableDefaultContentItems to false in the propertygroup node
-create the correct appsetting.json  and copy them to the directory of single exe file
-Run the exe as windows service: reproduce the issue.
If run the exe like a console the issue is not reproduced and the code 
configuration.GetSection("aaaaa")  read correctly the configuration

**Comment by Tratcher** [comment] 2019-12-04 16:03
Duplicate of https://github.com/aspnet/Extensions/issues/2148?

**Closed** 2019-12-04 16:18 UTC
